=== philschatz/stylish/src/xml-example/schemas/_autogen-design.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    
    <xs:complexType name="_Notes__Container"><xs:attribute name="box-decoration-break" use="optional" type="xs:string"><xs:annotation><xs:documentation>optional. The value needs to be a os:dunno-yet</xs:documentation></xs:annotation></xs:attribute></xs:complexType>

    <xs:complexType name="_Notes--Boxed__Title"><xs:attribute name="color" use="required" type="xs:string"><xs:annotation><xs:documentation>required. The value needs to be a os:color</xs:documentation></xs:annotation></xs:attribute><xs:attribute name="font-family" use="required" type="xs:string"><xs:annotation><xs:documentation>required. The value needs to be a os:font</xs:documentation></xs:annotation></xs:attribute><xs:attribute name="background-color" use="required" type="xs:string"><xs:annotation><xs:documentation>required. The value needs to be a os:color</xs:documentation></xs:annotation></xs:attribute><xs:attribute name="border-color" use="required" type="xs:string"><xs:annotation><xs:documentation>required. The value needs to be a os:color</xs:documentation></xs:annotation></xs:attribute></xs:complexType>

    <xs:complexType name="_Notes--Boxed__Body"><xs:attribute name="font-family" use="required" type="xs:string"><xs:annotation><xs:documentation>required. The value needs to be a os:font</xs:documentation></xs:annotation></xs:attribute><xs:attribute name="background-color" use="required" type="xs:string"><xs:annotation><xs:documentation>required. The value needs to be a os:color</xs:documentation></xs:annotation></xs:attribute></xs:complexType>
    
    <xs:complexType name="_Notes--Boxed__Subtitle"><xs:attribute name="color" use="required" type="xs:string"><xs:annotation><xs:documentation>required. The value needs to be a os:color</xs:documentation></xs:annotation></xs:attribute><xs:attribute name="font-family" use="required" type="xs:string"><xs:annotation><xs:documentation>required. The value needs to be a os:color</xs:documentation></xs:annotation></xs:attribute></xs:complexType>

    
    <xs:complexType name="_UnorderedList--NotesQuestionSection"><xs:attribute name="border-color" use="optional" type="xs:string"><xs:annotation><xs:documentation>optional. The value needs to be a os:color</xs:documentation></xs:annotation></xs:attribute></xs:complexType>

    
    <xs:element name="BoxedNoteWithSubtitleShape"><xs:annotation><xs:documentation>Defined in the design.xml file. Attributes: selector, box-decoration-break?, .</xs:documentation></xs:annotation><xs:complexType><xs:sequence><xs:element name="_Notes--Boxed__Title"><xs:annotation><xs:documentation>This is a component. For now it needs to be unique. Attributes: color, font-family, background-color, border-color.</xs:documentation></xs:annotation><xs:complexType><xs:complexContent><xs:extension base="_Notes--Boxed__Title"><xs:sequence/></xs:extension></xs:complexContent></xs:complexType></xs:element><xs:element name="_Notes--Boxed__Body"><xs:annotation><xs:documentation>This is a component. For now it needs to be unique. Attributes: font-family, background-color.</xs:documentation></xs:annotation><xs:complexType><xs:complexContent><xs:extension base="_Notes--Boxed__Body"><xs:sequence><xs:element name="_Notes--Boxed__Subtitle"><xs:annotation><xs:documentation>This is a component. For now it needs to be unique. Attributes: color, font-family.</xs:documentation></xs:annotation><xs:complexType><xs:complexContent><xs:extension base="_Notes--Boxed__Subtitle"><xs:sequence/></xs:extension></xs:complexContent></xs:complexType></xs:element><xs:element name="_UnorderedList--NotesQuestionSection"><xs:annotation><xs:documentation>This is a component. For now it needs to be unique. Attributes: border-color?.</xs:documentation></xs:annotation><xs:complexType><xs:complexContent><xs:extension base="_UnorderedList--NotesQuestionSection"><xs:sequence/></xs:extension></xs:complexContent></xs:complexType></xs:element></xs:sequence></xs:extension></xs:complexContent></xs:complexType></xs:element></xs:sequence><xs:attribute name="selector" use="required" type="xs:string"><xs:annotation><xs:documentation>This is the root selector that will match elements in the HTML document</xs:documentation></xs:annotation></xs:attribute><xs:attribute name="box-decoration-break" use="optional" type="xs:string"><xs:annotation><xs:documentation>optional. The value needs to be a os:dunno-yet</xs:documentation></xs:annotation></xs:attribute></xs:complexType></xs:element>

<xs:element name="book-root"><xs:annotation><xs:documentation>A dummy container for the root of the book</xs:documentation></xs:annotation><xs:complexType><xs:sequence><xs:element name="vars"><xs:annotation><xs:documentation>All of the variables that are used in the book need to be defined here</xs:documentation></xs:annotation><xs:complexType><xs:choice minOccurs="1" maxOccurs="unbounded"><xs:element name="var"><xs:annotation><xs:documentation>The id is used in curly braces inside shape/component definitions and are replaced with this value</xs:documentation></xs:annotation><xs:complexType><xs:attribute name="id" use="required" type="xs:string"/><xs:attribute name="value" use="required" type="xs:string"/></xs:complexType></xs:element></xs:choice></xs:complexType></xs:element><xs:element name="shapes"><xs:annotation><xs:documentation>All of the instances of shapes that are used in the book need to be defined here</xs:documentation></xs:annotation><xs:complexType><xs:choice minOccurs="1" maxOccurs="unbounded"><xs:element ref="BoxedNoteWithSubtitleShape"/></xs:choice></xs:complexType></xs:element></xs:sequence></xs:complexType></xs:element></xs:schema>

=== philschatz/stylish/src/xml-example/sociology.xml
<!-- See https://github.com/openstax/ce-styles/blob/main/styles/books/sociology/book.scss#L61-L71 -->
<book-root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./schemas/_autogen-design.xsd">

    <!-- Woot. Found unused code: Boxed__Body border-color="{colorMap:::boxedNoteBodyBackgroundOption2Color}" -->

    <vars>
        <var id="typography:::titleOption1Font" value="Archivo, sans-serif, StixGeneral" />
        <var id="typography:::titleOption2Font" value="IBM Plex Sans, sans-serif, StixGeneral" />
        <var id="typography:::titleOption3Font" value="Archivo Black, sans-serif, StixGeneral" />
        <var id="colorMap:::boxedNoteTitleColor" value="white" />
        <var id="colorMap:::boxedNoteTitleBorderColor" value="white" />
        <var id="colorMap:::fontBodyColor" value="black" />

        <!-- HACK: https://github.com/openstax/ce-styles/blob/bd4439f4004d156ac231c8e1f107114fcbfcd431/styles/designs/common/pdf/typography.scss#L19 -->
        <var id="font-scale(0)" value="1rem"/>
        <var id="font-scale(1)" value="1.2rem"/>
        <var id="line-height(0)" value="1rem"/>
        <var id="line-height(1)" value="1.5rem"/>
        <var id="v-spacing(1)" value="0.7rem"/>
        <var id="v-spacing(2)" value="1.4rem"/>

    </vars>

    <shapes>

        <BoxedNoteWithSubtitleShape
            selector=".sociology-big-picture">

        </BoxedNoteWithSubtitleShape>

    </shapes>

</book-root>
