=== philschatz/stylish/src/xml-example/schemas/framework.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="param">
    <xs:complexType>
        <xs:attribute name="name" use="required" type="xs:string"/>
        <xs:attribute name="required" use="required" type="xs:boolean"/>
        <xs:attribute name="type" use="required" type="xs:string"/>
    </xs:complexType>
</xs:element>

<xs:element name="component">
    <xs:complexType>
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element ref="param"/>
        </xs:choice>
        <xs:attribute name="name" use="required" type="xs:string"/>
        <xs:attribute name="subselector" use="required" type="xs:string"/>
    </xs:complexType>
</xs:element>

<xs:element name="component-ref">
    <xs:complexType>
        <xs:attribute name="ref" use="required" type="xs:string"/>
    </xs:complexType>
</xs:element>

<xs:element name="shape">
    <xs:complexType>
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element ref="param"/>
            <xs:element ref="component-ref"/>
        </xs:choice>
        <xs:attribute name="name" use="required" type="xs:string"/>
    </xs:complexType>
</xs:element>

<xs:element name="root">
    <xs:complexType>
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element ref="component"/>
            <xs:element ref="shape"/>
        </xs:choice>
    </xs:complexType>
</xs:element>

</xs:schema>

=== philschatz/stylish/src/xml-example/design.xml
<!--
  Compare this to the design.ts file.

  What this is: This will be used to generate a RelaxNG file that will validate the chemistry.xml file.

  Think of each of these are "classes" that are "instantiated" in a book or theme.
-->
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./schemas/framework.xsd">

    <component name="Title" subselector="[data-type='title']">
        <param name="fontFamily"  required="true" type="xs:string"/>
        <param name="color"       required="true" type="xs:string"/>
        <param name="fontWeight"  required="false" type="xs:string"/>
    </component>

    <shape name="BoxedNote">
        <param name="borderColor"       required="true" type="xs:string"/>
        <param name="groupBorderColor"  required="true" type="xs:string"/>
        <param name="groupBorderStyle"  required="false" type="SLICE_ENUM"/>
        <param name="groupBorderWidth"  required="false" type="Length"/>
        <param name="groupBoxDecorationBreak" required="false" type="SLICE_ENUM"/>

        <component-ref ref="Title"/>
    </shape>



    <component name="Container" subselector="[data-type='os-container']">
        <param name="columnCount"   required="true" type="xs:integer"/>
        <param name="columnGap"     required="true" type="Length"/>
        <param name="columnWidth"   required="true" type="xs:string"/>
    </component>

    <component name="ProblemNumber" subselector="[data-type='os-problem-number']">
        <param name="color" required="true" type="xs:string"/>
    </component>

    <component name="SectionMarginBottom" subselector="[data-type='os-problem-number']">
        <param name="marginBottom" required="true" type="xs:string"/>
    </component>

    <shape name="EOCAssessments">
        <component-ref ref="Container"/>
        <component-ref ref="ProblemNumber"/>
        <component-ref ref="SectionMarginBottom"/>
    </shape>
</root>
